### ISSUE TITLE
Support for Oculus Quest

### ISSUE THREAD

**Issue by kierepka** [WaveEngine/MixedRealityToolkit-WaveEngine#1]
Is it possible to run sample project on Oculus Quest?
[MRTK Oculus Quest](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/CrossPlatform/OculusQuestMRTK.html)

**Comment by LorenRd** [comment]
I'm also interested on this feature.

**Comment by minolo** [comment]
Hi there! Sorry for the delayed answer.

We are working on the OpenXR integration in WaveEngine, which will eventually support the Oculus Quest. You can see a little progress teaser [here](https://twitter.com/davilovick/status/1433364059999571973).

After that is done we will probably need to make some changes in the toolkit, since it has only been tested with the HoloLens 2.

Thanks for your interest in the tool!

**Comment by minolo** [comment]
Hi there!

Support for the Meta Quest device has been added in the recent releases. Thanks!
